version: "3.3"
services:
  nginx:
    build:
      context: containers/nginx
    ports:
      - 443:443
    networks:
      - vpn-localhost
  app-endpoint-server:
    build:
      context: ../../
      dockerfile: environments/local-PNG/containers/app-endpoint-server/Dockerfile
    ports:
      - '8081:8081'
    environment:
      XDG_RUNTIME_DIR: '/tmp'
    networks:
      - vpn-localhost
networks:
  vpn-localhost:
